#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Sync `core/` into `skills/0xkey-keyops-<role>/` for the multi-skill layout.

The repository keeps one editable source tree under `core/` and four role
skill packages under `skills/0xkey-keyops-<role>/`. Each role skill is fully
self-contained so it can be installed independently via `npx skills add`,
ClawHub, or zip upload, while `core/` remains the single place to edit shared
scripts, references, SECURITY / PRINCIPLES / WORKFLOWS docs, and the example
config.

Banner choice
-------------

Plan §1.1 originally suggested adding a per-file ``# AUTO-GENERATED ...; DO
NOT EDIT.`` header. We deliberately do NOT do that for two reasons:

1.  Drift detection becomes a simple SHA256 byte-equality check, which is
    cheap to run in CI and impossible to mis-implement.
2.  Mutating Python / JSON file bodies would change their hashes and risk
    desynchronizing them from any external integrity expectations (this
    skill is, after all, a key-ops skill where hashes matter).

Instead, each role skill directory gets a single ``_AUTO_GENERATED.md``
marker that points the reader back at this script. SKILL.md and that marker
are the only files in the role skill directory that are NOT byte-identical
copies of core/.

Usage
-----

::

    tools/sync-skills.py            # regenerate skills/<name>/ from core/
    tools/sync-skills.py --check    # exit 2 if any role skill has drifted

`--check` is the CI-callable form.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
CORE = REPO_ROOT / "core"
SKILLS = REPO_ROOT / "skills"

# Skill name → role doc stem under `core/references/roles/`.
ROLES: dict[str, str] = {
    "0xkey-keyops-coordinator": "coordinator",
    "0xkey-keyops-manifest": "manifest-set-member",
    "0xkey-keyops-share": "share-set-member",
    "0xkey-keyops-builder": "builder",
}

# Files copied from REPO_ROOT (not core/) into every role skill.
# These are kept outside core/ intentionally (e.g. VERSION is the single
# SemVer truth shared by the mono-repo root, not a core-layer detail).
REPO_ROOT_FILES: list[tuple[str, str]] = [
    ("VERSION", "VERSION"),
]

# Files copied into EVERY role skill (relative to CORE → role skill root).
SHARED_FILES: list[tuple[str, str]] = [
    ("SECURITY.md", "SECURITY.md"),
    ("PRINCIPLES.md", "PRINCIPLES.md"),
    ("config.prod.example.json", "config.prod.example.json"),
    ("references/operator-prompts.md", "references/operator-prompts.md"),
    ("references/provisioning-matrix.md", "references/provisioning-matrix.md"),
    ("references/qos-client-platform.md", "references/qos-client-platform.md"),
    ("references/release-notes.md", "references/release-notes.md"),
    ("references/workspace-rules.md", "references/workspace-rules.md"),
]

# WORKFLOWS.md is a full-ceremony narrative: only the Coordinator skill ships
# it. Manifest / Share / Builder agents must not read it (skill boundary).
COORDINATOR_ONLY_FILES: list[tuple[str, str]] = [
    ("WORKFLOWS.md", "WORKFLOWS.md"),
]

AUTO_GEN_MARKER_NAME = "_AUTO_GENERATED.md"
AUTO_GEN_MARKER_BODY = """\
# AUTO-GENERATED contents

Everything in this directory **except `SKILL.md` and this marker file** is
byte-identical to its source under the repository's `core/` directory and
is regenerated by `tools/sync-skills.py`.

If you need to change a shared script, runbook, or security rule, edit the
file under `core/` and re-run:

```bash
tools/sync-skills.py
```

`tools/sync-skills.py --check` runs in CI and exits non-zero if any role
skill has drifted from `core/`.
"""


def _expected_files(skill_name: str) -> list[tuple[Path, Path]]:
    role = ROLES[skill_name]
    out: list[tuple[Path, Path]] = []
    for src, dst in REPO_ROOT_FILES:
        out.append((REPO_ROOT / src, SKILLS / skill_name / dst))
    for src, dst in SHARED_FILES:
        out.append((CORE / src, SKILLS / skill_name / dst))
    if role == "coordinator":
        for src, dst in COORDINATOR_ONLY_FILES:
            out.append((CORE / src, SKILLS / skill_name / dst))
    out.append(
        (
            CORE / "references" / "roles" / f"{role}.md",
            SKILLS / skill_name / "references" / "roles" / f"{role}.md",
        )
    )
    return out


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_version() -> str:
    """Read the single-line VERSION file at the repo root.

    The repo-root `VERSION` is the single source of truth for the SemVer
    string carried in every per-role SKILL.md frontmatter, in CHANGELOG
    references, and in git tags. Errors here are fatal — we'd rather fail
    sync than ship a skill with no version line.
    """
    raw = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip()
    if not raw:
        raise RuntimeError("VERSION file is empty")
    if "\n" in raw or " " in raw:
        raise RuntimeError(
            f"VERSION file must contain a single SemVer token, got {raw!r}"
        )
    return raw


def _sync_skill_version(
    skill_md: Path, version: str, *, check: bool
) -> Optional[str]:
    """Ensure `skill_md`'s YAML frontmatter contains `version: <version>`.

    The frontmatter is hand-written (it carries the per-role description
    and the agent-skills triggering hints), so we cannot replace the
    whole file. We do a minimal, pure-string rewrite:

    * Locate the leading `---\\n ... \\n---\\n` block.
    * If a top-level `version:` line already exists, replace its value.
    * Otherwise insert `version: <version>` immediately after the
      mandatory `name:` line so the field appears in the same location
      every reader expects (compare `~/.agents/skills/lark-base/SKILL.md`).

    In `check` mode we report drift; in write mode we rewrite in place.
    Returns a drift message or None.
    """
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return f"{skill_md.relative_to(REPO_ROOT)}: missing YAML frontmatter"
    end = text.find("\n---\n", 4)
    if end < 0:
        return f"{skill_md.relative_to(REPO_ROOT)}: unterminated YAML frontmatter"
    fm_block = text[4:end + 1]  # body of frontmatter, ends with newline
    rest = text[end + 5:]        # everything after the closing `---\n`

    desired = f"version: {version}"
    fm_lines = fm_block.splitlines()
    new_fm_lines: list[str] = []
    found_version = False
    for line in fm_lines:
        # Match only top-level `version:` keys (not indented sub-fields).
        if line.startswith("version:") or line.startswith("version :"):
            if line.strip() == desired:
                found_version = True
                new_fm_lines.append(line)
            else:
                if check:
                    return (
                        f"{skill_md.relative_to(REPO_ROOT)}: version drift, "
                        f"expected {desired!r}, got {line.strip()!r}"
                    )
                new_fm_lines.append(desired)
                found_version = True
        else:
            new_fm_lines.append(line)

    if not found_version:
        if check:
            return (
                f"{skill_md.relative_to(REPO_ROOT)}: missing top-level "
                f"{desired!r} in frontmatter"
            )
        # Insert just after the `name:` line; that line is mandatory in
        # the repo's SKILL.md template.
        for i, line in enumerate(new_fm_lines):
            if line.startswith("name:"):
                new_fm_lines.insert(i + 1, desired)
                break
        else:
            new_fm_lines.insert(0, desired)

    new_fm_block = "\n".join(new_fm_lines) + "\n"
    new_text = "---\n" + new_fm_block + "---\n" + rest
    if new_text != text:
        if check:
            return (
                f"{skill_md.relative_to(REPO_ROOT)}: SKILL.md frontmatter "
                "would be rewritten by sync (run sync-skills.py)"
            )
        skill_md.write_text(new_text, encoding="utf-8")
    return None


def _sync_one(skill_name: str, *, check: bool, version: str) -> list[str]:
    drift: list[str] = []
    skill_dir = SKILLS / skill_name
    skill_md = skill_dir / "SKILL.md"

    if not skill_md.exists():
        drift.append(f"{skill_name}: missing hand-written SKILL.md")
        return drift

    msg = _sync_skill_version(skill_md, version, check=check)
    if msg is not None:
        drift.append(msg)

    expected_pairs = _expected_files(skill_name)

    def _src_label(p: Path) -> str:
        try:
            return f"core/{p.relative_to(CORE)}"
        except ValueError:
            return str(p.relative_to(REPO_ROOT))

    for src, dst in expected_pairs:
        if not src.exists():
            drift.append(f"{skill_name}: missing source {_src_label(src)}")
            continue
        src_label = _src_label(src)
        if check:
            if not dst.exists():
                drift.append(
                    f"{skill_name}: missing copy {dst.relative_to(REPO_ROOT)}"
                )
                continue
            if _sha256(src) != _sha256(dst):
                drift.append(
                    f"{skill_name}: drift {dst.relative_to(REPO_ROOT)} "
                    f"!= {src_label}"
                )
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)

    marker = skill_dir / AUTO_GEN_MARKER_NAME
    if check:
        if not marker.exists():
            drift.append(f"{skill_name}: missing {AUTO_GEN_MARKER_NAME}")
        elif marker.read_text(encoding="utf-8") != AUTO_GEN_MARKER_BODY:
            drift.append(
                f"{skill_name}: {AUTO_GEN_MARKER_NAME} drifted from expected body"
            )
    else:
        marker.write_text(AUTO_GEN_MARKER_BODY, encoding="utf-8")

    expected_paths = {dst.relative_to(skill_dir) for _, dst in expected_pairs}
    expected_paths.add(Path("SKILL.md"))
    expected_paths.add(Path(AUTO_GEN_MARKER_NAME))

    if skill_dir.exists():
        for path in skill_dir.rglob("*"):
            if path.is_dir():
                continue
            rel = path.relative_to(skill_dir)
            if rel in expected_paths:
                continue
            if check:
                drift.append(
                    f"{skill_name}: stale file {rel} (not in core/ fan-out)"
                )
            else:
                path.unlink()

    if not check and skill_dir.exists():
        # Remove empty dirs left behind after stale-file cleanup. We sort
        # deepest-first so child dirs disappear before their parents.
        for d in sorted(
            (p for p in skill_dir.rglob("*") if p.is_dir()),
            key=lambda p: len(p.parts),
            reverse=True,
        ):
            try:
                d.rmdir()
            except OSError:
                continue

    return drift


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--check",
        action="store_true",
        help="exit 2 if any role skill is missing files or drifts from core/; "
        "make no changes",
    )
    return p


def main() -> int:
    ns = _build_parser().parse_args()
    version = _read_version()
    all_drift: list[str] = []
    for skill_name in ROLES:
        all_drift.extend(_sync_one(skill_name, check=ns.check, version=version))

    if all_drift:
        for line in all_drift:
            print(line, file=sys.stderr)
        return 2 if ns.check else 1

    if ns.check:
        print(f"OK: {len(ROLES)} role skills match core/ (version {version})")
    else:
        print(f"synced {len(ROLES)} role skills from core/ (version {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
